# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('organisation_id', models.CharField(max_length=64)),
                ('dataset_id', models.CharField(max_length=64)),
                ('statistic', models.CharField(max_length=32)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
